# Generated by Django 3.2.5 on 2021-08-02 14:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.SmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField(blank=True)),
                ('sq_ft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('photo_main', models.ImageField(blank=True, upload_to='Photos/%Y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='Photos/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='Photos/%Y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, upload_to='Photos/%Y/%m/%d')),
                ('photo_4', models.ImageField(blank=True, upload_to='Photos/%Y/%m/%d')),
                ('photo_5', models.ImageField(blank=True, upload_to='Photos/%Y/%m/%d')),
                ('photo_6', models.ImageField(blank=True, upload_to='Photos/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(default=datetime.datetime.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors_app.realtor')),
            ],
        ),
    ]
